baseURL = '/'
languageCode = 'zh-CN'
title = '小舟从此逝，江海寄余生'
theme = 'brume'
paginate = 8

[params]
  description = '记录技术、思考与生活、大模型科普知识'
  author = 'Fancy'
  copyright = '© 2026 Fancy · 用文字记录思考'
  github = 'https://github.com'

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    noClasses = false

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '主页'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'archive'
    name = '归档'
    url = '/archive/'
    weight = 2
  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/about/'
    weight = 3

[outputs]
  home = ['HTML', 'RSS']
